# Generated by Django 5.0.1 on 2024-01-25 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='задача')),
                ('description', models.TextField(verbose_name='описание')),
                ('deadline', models.DateTimeField(verbose_name='дедлайн')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('status', models.CharField(choices=[('OP', 'Открытая'), ('CL', 'Закрытая'), ('EX', 'Срочная'), ('OV', 'Просроченная')], default='OP', max_length=2, verbose_name='статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
